format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$character"""

add_newline = false

[username]
style_root = 'dimmed red'
style_user = 'dimmed white'
format = '[$user]($style)'

[hostname]
style = 'dimmed white'
format = '[@$hostname]($style) '

[directory]
style = 'bold green'

[git_branch]
style = "italic dimmed white"
format = "[$branch(:$remote_branch)]($style) "

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[<](bold green)'
